### ISSUE TITLE
readme line 12 

### ISSUE THREAD

**Issue by Chanez89** [learn-co-curriculum/phase-4-creating-a-rails-app-readme#2]
### Canvas Link

https://learning.flatironschool.com/courses/4379/pages/creating-a-rails-app?module_item_id=318646

### Concern

file - README

Line 12 -  "This video will cover same the content in the readme below, so it's recommended"

"same the" is in the wrong order

### Suggested Changes

"This video will cover the same content in the readme below, so it's recommended"

correct order

**Comment by lizbur10** [comment]
Thanks for bringing this to our attention @Chanez89 ! It has now been fixed 💙
